### ISSUE TITLE
Getting blocked by CloudFalre

### ISSUE THREAD

**Issue by panthernet** [zKillboard/RedisQ#13]
Until some recent changes it worked correclty for me. I were able to query the RedisQ with **https://redisq.zkillboard.com/listen.php?ttw=1** and now I'm getting blocked. I even added a 3 seconds delay on getting null data from the request but it won't work. I'm still getting banned.

Please advice on possible solution for this issue. I want to suppliy my bot with the ZKB killmail livestream.

PS: bot uses different a bit randomized http header for request for each bot instance to distinct them

**Comment by cvweiss** [comment]
I recently blocked several dozen IP addresses that had multiple requests in flight at one time generating http code 429 errors. Please read the instructions and fix your code so that one request to RedisQ happens at a time. Failure to do so will mean you will continue to be banned.

> PS: bot uses different a bit randomized http header for request for each bot instance to distinct them

Don't to do this. Write our code to execute properly and disseminate information accordingly. 

Once you've fixed your code, come to Tweetfleet and speak with Squizz via private message. Thank you.

**Comment by panthernet** [comment]
Sorry is this applied to https://redisq.zkillboard.com/listen.php or for ANY requests to Zkb ? Even the ones from the https://zkillboard.com/api/kills/characterID ?

**Comment by cvweiss** [comment]
Blanket ban on the zkillboard.com domain.

**Comment by panthernet** [comment]
No I mean did your security system run similar check for https://zkillboard.com/api/kills/characterID for instance? Had no offence in might just want to make it clear so I can fix it.

**Comment by panthernet** [comment]
On the other hand it won;t matter much for me I suppose. Thanks for the reply.
